# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b567c67e25e5b6a5b557912bc9cd314ec803a676e0fd65483a8b53155e02611f099792bd7e7cad41c0207fb14ca8b09b2dbd07468829add3152d7cc8ee77ab29

test:
  secret_key_base: f89c49f8303a7ceb64ee61a5d6895f325444b8e4f445bf63647d5f788beabdca6288be7bd9f64601002030c4232a232acf4e1a5d212150a2aee720280703bff5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
